---
- name: git clone dots
  git: >
    repo=git://github.com/Ceasar/dots.git
    dest=/home/{{ username }}/dots
    accept_hostkey=yes
    force=yes
  when: username is defined
- name: install dependencies
  sudo: true
  pip: chdir=/home/{{ username }}/dots requirements=requirements.txt
- name: mkdir dots/plugins
  file: path=/home/{{ username }}/dots/plugins state=directory
  when: username is defined
- name: git clone dotfiles
  git: repo={{ dotfiles }}
       recursive=yes
       dest=/home/{{ username }}/dots/plugins/dotfiles
       ssh_opts="-o StrictHostKeyChecking=no"
       force=yes
  when: username is defined and dotfiles is defined
- name: pip install requirements
  pip: requirements=/home/{{ username }}/dots/requirements.txt extra_args='--user'
  when: username is defined
- name: rm .bashrc
  file: path=/home/{{ username }}/.bashrc state=absent
  when: username is defined
- name: fab link:plugins
  command: fab link:plugins chdir=/home/{{ username }}/dots
  args:
    creates: /home/{{ username }}/.vim
  when: username is defined
