j--
- name: update apt cache
  apt: update_cache=yes
  sudo: true
- name: install apt packages
  apt: pkg={{ item }} state=latest
  sudo: true
  with_items:
    - vim
    - vim-nox
    - tmux
    - exuberant-ctags
    - ack-grep
    - mercurial
    - python-pip
    - python-dev
    - git-all
    - git-flow
    - curl
    - default-jdk
    - libxml2-dev
    - ruby-bundler
    - tree
    - procps
- name: install autoenv
  pip: name=autoenv state=latest
  sudo: true
- name: ack divert
  command: /usr/bin/dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep creates=/usr/bin/ack
  sudo: true
